server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bubble_translation"
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

auth:
  jwt:
    secret: toanhuynguyen
    expirationMs: 900000 # 15 phut
    refreshExpirationMs: 604800000 #7 ngay
